# Dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: label
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, label]
    item: [item_id,book_title,book_author,publication_year,publisher]
    user: [user_id,location,age]
user_inter_num_interval: [13,100]

# Training and evaluation config
epochs: 50   # 30
train_batch_size: 32
valid_metric: mrr@5

# Evaluate config
eval_args:
    group_by: task
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode : labeled

# Meta learning config
meta_args:
    support_num: none
    query_num: 10

# MetaEmb Parameters
embedding: 32
indexEmbDim: 8
modelRecHiddenDim: 32
pretrainEpoch: 20
pretrainLr: 0.0001
embeddingGeneratorHiddenDim: 32
localLr: 0.0001
alpha: 0.2
lr: 0.0001


# Metrics
metrics: ['precision','recall','hit','ndcg','mrr']
metric_decimal_place: 4
topk: 5